apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: devops-challenge-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "YourStrong@Passw0rd"
            - name: MYSQL_DATABASE
              value: "challengedb"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: devops-challenge-ns
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
